routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::resource('sources', 'SourcesController');

Route::get('/feeds/', 'FeedsController@index')->name('feeds');
Route::post('/feed/add', 'FeedsController@addFeed')->name('add-feed');
Route::get('/feed/{feed}/delete', 'FeedsController@deleteFeed')->name('delete-feed');

Route::get('/news', 'NewsController@index')->name('index-news');
Route::get('/news/{news}/edit', 'NewsController@edit')->name('edit-news');
Route::post('/news/{news}/update', 'NewsController@update')->name('update-news');

app/Sources.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Sources
 * @package App
 */
class Sources extends Model
{
    use Sluggable;

    /**
     * @var array
     */
    protected $fillable = ['source_name'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function feeds()
    {
        return $this->hasMany('App\Feeds');
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'source_name'
            ]
        ];
    }

    /**
     * Get total news for source
     * @return int
     */
    public function getTotalNews()
    {
        $totalNews = 0;
        foreach ($this->feeds as $feeds)
        {
            $totalNews += $feeds->news->count();
        }

        return $totalNews;
    }
}

app/Http/Controllers/SourcesController.php
<?php

namespace App\Http\Controllers;

use App\Sources;
use Illuminate\Http\Request;

/**
 * Class SourcesController
 * @package App\Http\Controllers
 */
class SourcesController extends Controller
{
    /**
     * SourcesController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $sources = Sources::all();

        return view('sources.index', [
            'sources' => $sources
        ]);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('sources.create', [

        ]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $source = new Sources([
           'source_name' => $request->source_name
        ]);
        $source->save();

        return redirect()->route('sources.edit', ['slug' => $source->slug]);
    }

    /**
     * @param Request $request
     * @param Sources $slug
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Request $request, $slug)
    {
        $source = Sources::where('slug', $slug)->first();

        return view('sources.edit', [
            'source' => $source
        ]);
    }
}

resources/views/sources/create.blade.php
@extends('tabler::layouts.main')

@push('scripts')
    <script src="{{ asset('js/pages/sources.js') }}"></script>
@endpush

@section('title')
    Creating new Source
@stop

@section('content')
    <div class="col-6">
        <div class="row">
            <div class="card">
                <div class="card-status bg-teal"></div>
                <div class="card-header">
                    <h3 class="card-title">Source Form</h3>
                </div>
                <form action="{{ route('sources.store') }}" method="post">
                    {{csrf_field()}}
                    <div class="card-body">
                        <div class="form-group">
                            <label class="form-label">Source Display Name</label>
                            <input type="text" class="form-control" name="source_name" value="" placeholder="Metro Feeds">
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button class="btn btn-cyan" type="submit"><i class="fe fe-plus"></i> Add Source</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop

resources/views/sources/edit.blade.php
@extends('tabler::layouts.main')

@push('scripts')
    <script src="{{ asset('js/pages/sources.js') }}"></script>
@endpush

@section('title')
    Editing Source: {{ $source->source_name }}
@stop

@section('content')
    <div class="col-6">
        <div class="row">
            <div class="card">
                <div class="card-status bg-teal"></div>
                <div class="card-header">
                    <h3 class="card-title">Source Edit</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label class="form-label">Source Name</label>
                        <input type="text" class="form-control" name="source_name" value="{{ $source->source_name }}">
                    </div>
                </div>
                <div class="card-alert alert alert-success mb-0">
                    Source Feeds
                    <div class="card-options float-right">
                        <button class="btn btn-cyan btn-sm"
                                data-toggle="modal"
                                data-target="#newFeedModal"
                                data-backdrop="static"
                                data-keyboard="false"
                        >
                            <i class="fe fe-plus"></i> add feed
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="list-group list-group-transparent mb-0 feeds-list">
                        @foreach($source->feeds as $feed)
                            <span class="list-group-item list-group-item-action align-items-center border-bottom pl-0 pr-0">
                                <div class="float-left item-url">{{ $feed->url }}</div>
                                <a href="" class="float-right text-danger delete-feed-btn"
                                   data-url="{{ route('delete-feed', ['feed' => $feed]) }}"
                                   data-sourceid="{{ $feed->sources_id }}"
                                   data-feedid="{{ $feed->id }}"
                                ><i class="fe fe-trash"></i></a>
                            </span>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('modal')
    <div class="modal" id="newFeedModal" tabindex="-1" role="dialog" aria-labelledby="newFeedModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="dimmer">
                    <div class="loader"></div>
                    <div class="dimmer-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLongTitle">Adding A Feed</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            </button>
                        </div>
                        <form action="{{ route('add-feed') }}" class="new-feed-form">
                            {{ csrf_field() }}
                            <div class="modal-body">
                                <div class="form-group">
                                    <label class="form-label">Feed Url</label>
                                    <input type="text" class="form-control" name="url" placeholder="http://news.feed/xml">
                                </div>
                            </div>
                            <div class="modal-footer">
                                <input type="hidden" name="source_id" value="{{ $source->id }}">
                                <button type="submit" class="btn btn-cyan new-feed-btn"><i class="fe fe-check"></i> Add Feed</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@stop

resources/views/sources/index.blade.php
@extends('tabler::layouts.main')

@push('styles')
@endpush

@section('title')
    Sources List
@stop

@section('card-options')
    <a href="{{ route('sources.create') }}" class="btn btn-cyan btn-sm"><i class="fe fe-plus"></i> Add new Source</a>
@stop

@section('content')
    @if ($sources->count() == 0)
        <div class="alert alert-primary" role="alert">
            Source list empty
        </div>
    @else
        <div class="row row-cards row-deck">
            <div class="col-12">
                <div class="card">
                    <div class="table-responsive">
                        <table class="table table-hover table-outline table-vcenter text-nowrap card-table">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th class="text-center">Last fetched on</th>
                                <th class="text-center">Total Feed</th>
                                <th class="text-center">Total News</th>
                                <th class="text-right"><i class="fe fe-settings"></i></th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach($sources as $source)
                                    <tr>
                                        <td>{{ $source->source_name }}</td>
                                        <td class="text-center">
                                            {{ $source->last_fetched_on ?? 'Never' }}
                                        </td>
                                        <td>
                                            <div class="mx-auto chart-circle chart-circle-xs" data-value="{{ $source->feeds->count() }}" data-thickness="3" data-color="orange">
                                                <div class="chart-circle-value">{{ $source->feeds->count() }}</div>
                                            </div>
                                        </td>
                                        <td class="text-center">
                                            <div class="mx-auto chart-circle chart-circle-xs" data-value="1" data-thickness="3" data-color="blue">
                                                <div class="chart-circle-value">{{ $source->getTotalNews() }}</div>
                                            </div>
                                        </td>
                                        <td class="text-right">
                                            <a href="{{ route('sources.edit', ['slug' => $source->slug]) }}"><i class="fe fe-edit"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    @endif
@stop